#!/usr/bin/env bash
#
# lazy-bootstrap, shell edition.
#
# The same pipeline as the Python driver, written so a human can read it top to
# bottom and re-run any single stage by hand (docs/SPECS.md D-01, D-17):
#
#     inventory -> preflight -> prepare builder -> per package: fetch, deps,
#     build -> report
#
# It emits the *same* report.json schema, so the Python renderers work on its
# output too:
#
#     sh/lazy-bootstrap.sh rebuild debian:13-slim --package hostname
#     ./lazy-bootstrap report runs/<id> --format html
#
# What it deliberately does not do (use the Python driver for these): the HTML
# and comparison renderers, the toolchain matrix in one invocation, parallel
# build units, and the hostfs/overlay rootfs modes. Everything those need is
# reporting or orchestration, not pipeline - and this file's job is to make the
# pipeline legible.
#
# Debug levels, identical to the Python side:
#     LB_DEBUG=0  quiet   1  steps+rc+timing   2  +payload   3  +full output
#
set -uo pipefail

VERSION="0.1.0"
SELF="$(basename "$0")"

# --------------------------------------------------------------------------
# defaults
# --------------------------------------------------------------------------
IMAGE=""
BACKEND="podman"          # host | chroot | bwrap | firejail | podman | docker
ROOTFS="image"            # image[:REF] | dir:PATH | none
ROOTFS_PATH=""
WORKDIR="/build"
TOOLCHAIN="gcc"
FILC_VERSION="0.681"
REGISTRY_MIRROR=""
SOURCE_MIRROR=""
SYSTEM_DEPS="target"      # off | target | host
OUT_DIR="runs"
CACHE_DIR="${LAZY_BOOTSTRAP_CACHE:-/var/cache/lazy-bootstrap}"
TIMEOUT=1800
LIMIT=0
SELECT=()
LB_DEBUG="${LB_DEBUG:-0}"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SYSDEPS_DIR="$ROOT_DIR/ci/system-deps"

SHIM_DIR=/opt/lazy-bootstrap/shim
TC_ROOT=/opt/lazy-bootstrap/toolchains

# --------------------------------------------------------------------------
# output helpers
# --------------------------------------------------------------------------
say()  { printf '\n\033[1;35m::\033[0m \033[1m%s\033[0m\n' "$*"; }
info() { printf '\033[0;36m%s\033[0m\n' "$*" >&2; }
warn() { printf '\033[0;33mwarning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[0;31merror:\033[0m %s\n' "$*" >&2; exit 2; }

STEP_N=0
REPLAY=""

# step_begin <id-prefix> <title>  - announces a step and records it for replay
step_begin() {
    STEP_N=$((STEP_N + 1))
    STEP_ID="$(printf '%s#%04d' "$1" "$STEP_N")"
    STEP_TITLE="$2"
    STEP_START="$(date +%s.%N)"
    [ "$LB_DEBUG" -ge 1 ] && printf '\n\033[1;35m::\033[0m \033[1m%s\033[0m %s\n' \
        "$STEP_ID" "$STEP_TITLE" >&2
    return 0
}

# step_end <rc> [output]
step_end() {
    local rc="$1" out="${2:-}" secs
    secs="$(awk -v a="$STEP_START" -v b="$(date +%s.%N)" 'BEGIN{printf "%.1f", b-a}')"
    STEP_SECONDS="$secs"
    if [ "$LB_DEBUG" -ge 1 ]; then
        if [ "$rc" = 0 ]; then printf '   -> \033[0;32mok\033[0m in %ss\n' "$secs" >&2
        else printf '   -> \033[0;31mrc=%s\033[0m in %ss\n' "$rc" "$secs" >&2; fi
    fi
    if [ -n "$out" ] && { [ "$LB_DEBUG" -ge 3 ] || { [ "$rc" != 0 ] && [ "$LB_DEBUG" -ge 1 ]; }; }; then
        printf '%s\n' "$out" | sed 's/^/     > /' >&2
    fi
    return 0
}

# replay_add <command...> - append a runnable line to the replay script
replay_add() {
    [ -n "$REPLAY" ] || return 0
    {
        printf '\n# ---- %s  %s\n' "$STEP_ID" "$STEP_TITLE"
        printf 'step'
        printf ' %q' "$@"
        printf '\n'
    } >> "$REPLAY"
}

replay_init() {
    REPLAY="$1"
    mkdir -p "$(dirname "$REPLAY")"
    cat > "$REPLAY" <<'EOF'
#!/bin/sh
# Replay script generated by sh/lazy-bootstrap.sh.
# Every `step` line is exactly what the tool ran, wrapper included, in order.
#   sh replay.sh              run it
#   LB_REPLAY_DRY=1 sh ...    print without running
set -u
step() {
    printf '\n\033[1;35m::\033[0m %s\n' "$*"
    [ "${LB_REPLAY_DRY:-0}" = 1 ] && return 0
    "$@"
}
EOF
    chmod +x "$REPLAY"
}

# --------------------------------------------------------------------------
# the executor: one function per backend, all with the same signature
#
#   env_run <script>   run a POSIX shell script inside the environment
#
# ENV_ARGV is the wrapper prefix; everything else is shared. This is the shell
# equivalent of the Executor class (docs/SPECS.md D-04).
# --------------------------------------------------------------------------
CONTAINER=""
ROOTFS_DIR=""
declare -a ENV_ARGV=()
declare -a ENV_VARS=()

env_open() {
    case "$BACKEND" in
        host)
            ENV_ARGV=(/bin/sh -c)
            mkdir -p "$WORKDIR"
            ;;
        podman|docker)
            local image; image="$(resolve_image "$IMAGE")"
            step_begin session "start container from $image"
            CONTAINER="lb-sh-$$-$RANDOM"
            replay_add "$BACKEND" run --detach --name "$CONTAINER" "$image" sleep infinity
            local out; out="$("$BACKEND" run --detach --name "$CONTAINER" \
                              "$image" sleep infinity 2>&1)"
            step_end "$?" "$out"
            [ -n "$out" ] || die "could not start container"
            ENV_ARGV=("$BACKEND" exec "$CONTAINER" /bin/sh -c)
            env_run "mkdir -p $WORKDIR" >/dev/null
            ;;
        chroot|bwrap|firejail)
            ROOTFS_DIR="$(materialise_rootfs)"
            mkdir -p "$ROOTFS_DIR$WORKDIR"
            case "$BACKEND" in
                chroot)
                    for m in proc sys dev; do mkdir -p "$ROOTFS_DIR/$m"; done
                    mount -t proc proc "$ROOTFS_DIR/proc" 2>/dev/null || true
                    mount -t tmpfs -o mode=1777 tmpfs "$ROOTFS_DIR/tmp" 2>/dev/null || true
                    mount --rbind /dev "$ROOTFS_DIR/dev" 2>/dev/null || true
                    cp -f /etc/resolv.conf "$ROOTFS_DIR/etc/resolv.conf" 2>/dev/null || true
                    ENV_ARGV=(chroot "$ROOTFS_DIR" /bin/sh -c)
                    ;;
                bwrap)
                    # --perms 1777 on /tmp: apt drops privileges to `_apt`.
                    ENV_ARGV=(bwrap --bind "$ROOTFS_DIR" / --proc /proc --dev /dev
                              --perms 1777 --tmpfs /tmp --die-with-parent --unshare-pid
                              --ro-bind /etc/resolv.conf /etc/resolv.conf
                              /bin/sh -c)
                    ;;
                firejail)
                    ENV_ARGV=(firejail --quiet --noprofile "--chroot=$ROOTFS_DIR"
                              --caps.drop=all /bin/sh -c)
                    ;;
            esac
            ;;
        *) die "unknown backend: $BACKEND" ;;
    esac
}

env_close() {
    case "$BACKEND" in
        podman|docker)
            [ -n "$CONTAINER" ] && "$BACKEND" rm -f -t 0 "$CONTAINER" >/dev/null 2>&1
            ;;
        chroot)
            for m in dev proc; do umount -l "$ROOTFS_DIR/$m" 2>/dev/null || true; done
            ;;
    esac
}

# env_run <script> - stdout is the script's output, ENV_RC holds the exit code
env_run() {
    local script="$1"
    local prologue="cd $WORKDIR 2>/dev/null || true"
    local body="$prologue
$script"
    local -a argv=()
    if [ "${#ENV_VARS[@]}" -gt 0 ]; then
        argv=(env "${ENV_VARS[@]}" "${ENV_ARGV[@]}" "$body")
    else
        argv=("${ENV_ARGV[@]}" "$body")
    fi
    if [ "$LB_DEBUG" -ge 2 ]; then
        printf '   run: %s\n' "${argv[*]:0:${#argv[@]}-1}" >&2
        printf '%s\n' "$script" | sed 's/^/     | /' >&2
    fi
    replay_add "${argv[@]}"
    local out; out="$("${argv[@]}" 2>&1)"
    ENV_RC=$?
    printf '%s' "$out"
    return 0
}

# env_run_step <prefix> <title> <script> - the traced form used by the pipeline
env_run_step() {
    step_begin "$1" "$2"
    local out; out="$(env_run "$3")"
    step_end "$ENV_RC" "$out"
    LAST_OUTPUT="$out"
    return 0
}

env_put() {   # env_put <host file> <target path>
    case "$BACKEND" in
        host)              mkdir -p "$(dirname "$2")"; cp -a "$1" "$2" ;;
        podman|docker)     "$BACKEND" cp "$1" "$CONTAINER:$2" ;;
        chroot|bwrap|firejail)
            mkdir -p "$(dirname "$ROOTFS_DIR$2")"; cp -a "$1" "$ROOTFS_DIR$2" ;;
    esac
}

env_write() { # env_write <target path> <mode> <<< content
    local target="$1" mode="${2:-0644}" tmp
    tmp="$(mktemp)"
    cat > "$tmp"
    env_put "$tmp" "$target"
    env_run "chmod $mode $target" >/dev/null
    rm -f "$tmp"
}

# --------------------------------------------------------------------------
# images and rootfs
# --------------------------------------------------------------------------
resolve_image() {
    local ref="$1"
    case "$ref" in */*/*) ;; */*) ref="docker.io/$ref" ;; *) ref="docker.io/library/$ref" ;; esac
    case "$ref" in *:*) ;; *) ref="$ref:latest" ;; esac
    [ -n "$REGISTRY_MIRROR" ] && ref="${ref/docker.io/$REGISTRY_MIRROR}"
    printf '%s' "$ref"
}

materialise_rootfs() {
    case "$ROOTFS" in
        dir:*)  printf '%s' "${ROOTFS#dir:}"; return 0 ;;
        none)   printf '/'; return 0 ;;
    esac
    local image dest
    image="$(resolve_image "${ROOTFS#image:}")"
    [ "$ROOTFS" = image ] && image="$(resolve_image "$IMAGE")"
    dest="${ROOTFS_PATH:-$CACHE_DIR/rootfs/$(printf '%s' "$image" | tr -c 'a-zA-Z0-9._-' '-')}"
    if [ -f "$dest/.lb-stamp" ]; then printf '%s' "$dest"; return 0; fi

    step_begin rootfs "export $image -> $dest"
    mkdir -p "$dest"
    local engine="podman"; command -v podman >/dev/null || engine="docker"
    local name="lb-export-$$"
    "$engine" pull "$image" >/dev/null 2>&1
    "$engine" create --name "$name" "$image" true >/dev/null 2>&1
    "$engine" export "$name" | tar -x -C "$dest"
    local rc=$?
    "$engine" rm -f -t 0 "$name" >/dev/null 2>&1
    step_end "$rc"
    [ "$rc" = 0 ] || die "could not export $image"
    : > "$dest/.lb-stamp"
    printf '%s' "$dest"
}

# --------------------------------------------------------------------------
# distro detection and drivers
# --------------------------------------------------------------------------
DISTRO=""      # debian | alpine
DISTRO_ID=""   # what the image calls itself
DISTRO_VERSION=""
LIBC=""
ARCH=""

detect_distro() {
    env_run "test -e /sbin/apk || test -e /etc/alpine-release" >/dev/null
    if [ "$ENV_RC" = 0 ]; then DISTRO=alpine; else DISTRO=debian; fi

    if [ "$DISTRO" = alpine ]; then
        DISTRO_ID=alpine
        DISTRO_VERSION="$(env_run 'cat /etc/alpine-release 2>/dev/null' | tr -d '\n')"
        ARCH="$(env_run 'apk --print-arch 2>/dev/null || uname -m' | tr -d '\n')"
    else
        DISTRO_ID="$(env_run '. /etc/os-release 2>/dev/null; echo "$ID"' | tr -d '\n')"
        DISTRO_VERSION="$(env_run '. /etc/os-release 2>/dev/null; echo "$VERSION_ID"' | tr -d '\n')"
        ARCH="$(env_run 'dpkg --print-architecture 2>/dev/null || uname -m' | tr -d '\n')"
    fi
    LIBC="$(env_run 'if ls /lib/ld-musl-*.so.* >/dev/null 2>&1; then echo musl;
        elif ls /lib*/ld-linux*.so.* /lib/*/ld-linux*.so.* >/dev/null 2>&1; then echo glibc;
        else echo unknown; fi' | tr -d '\n')"
    info "environment: ${DISTRO_ID:-$DISTRO} $DISTRO_VERSION ($ARCH, $LIBC) [driver: $DISTRO]"
}

# inventory -> lines of "binary<TAB>version<TAB>arch<TAB>source"
distro_inventory() {
    if [ "$DISTRO" = alpine ]; then
        env_run "awk '
            /^P:/ {n=substr(\$0,3)} /^V:/ {v=substr(\$0,3)}
            /^A:/ {a=substr(\$0,3)} /^o:/ {o=substr(\$0,3)}
            /^\$/ {if (n != \"\") printf \"%s\t%s\t%s\t%s\n\", n, v, a, (o==\"\"?n:o);
                   n=\"\"; v=\"\"; a=\"\"; o=\"\"}
            END  {if (n != \"\") printf \"%s\t%s\t%s\t%s\n\", n, v, a, (o==\"\"?n:o)}
        ' /lib/apk/db/installed"
    else
        env_run 'dpkg-query -W -f='"'"'${binary:Package}\t${Version}\t${Architecture}\t${source:Package}\n'"'"''
    fi
}

# packages declared for one component in ci/system-deps (docs/SPECS.md D-24)
sysdeps_for() {
    local component="$1" file="$SYSDEPS_DIR/$DISTRO/$1.txt"
    [ -f "$file" ] || return 0
    sed 's/#.*//' "$file" | tr -s ' \n' '\n' | grep -v '^$' | tr '\n' ' '
}

sysdeps_install() {
    local component="$1" pkgs; pkgs="$(sysdeps_for "$component")"
    [ -n "${pkgs// /}" ] || return 0
    if [ "$SYSTEM_DEPS" = off ] || { [ "$BACKEND" = host ] && [ "$SYSTEM_DEPS" != host ]; }; then
        warn "not installing system-deps for '$component' (policy: $SYSTEM_DEPS): $pkgs"
        NOTES+=("system-deps for '$component' not installed (policy $SYSTEM_DEPS): $pkgs")
        return 0
    fi
    if [ "$DISTRO" = alpine ]; then
        env_run_step sysdeps "system-deps ($component): $pkgs" "apk add --no-cache $pkgs"
    else
        env_run_step sysdeps "system-deps ($component): $pkgs" \
            "export DEBIAN_FRONTEND=noninteractive
apt-get update -o Acquire::Retries=3 >/dev/null || true
apt-get install -y --no-install-recommends $pkgs"
    fi
}

prepare_builder() {
    if [ "$DISTRO" = alpine ]; then
        env_run_step prepare "apk update" "apk update"          # advisory (D-24)
        sysdeps_install common
        env_run_step prepare "abuild keygen" \
            'adduser -D -G abuild builder 2>/dev/null || true
export PACKAGER="lazy-bootstrap <noreply@example.invalid>"
ls /root/.abuild/*.rsa >/dev/null 2>&1 || abuild-keygen -a -i -n'
        local branch="${SOURCE_MIRROR:-$(printf '%s' "$DISTRO_VERSION" |
            awk -F. '{printf "%s.%s-stable", $1, $2}')}"
        env_run_step prepare "clone aports ($branch)" \
            "cd $WORKDIR
[ -d aports/.git ] && exit 0
git clone --depth 1 --filter=blob:none --sparse --branch $branch \
    https://github.com/alpinelinux/aports.git aports
cd aports && git sparse-checkout init --cone"
    else
        # deb-src cloned from whatever binary sources the image already has,
        # unless an explicit mirror was given (docs/SPECS.md D-20).
        if [ -n "$SOURCE_MIRROR" ]; then
            set -- $SOURCE_MIRROR
            env_run_step prepare "configure source mirror" \
                "printf 'Types: deb-src\nURIs: %s\nSuites: %s\nComponents: %s\nTrusted: yes\n' \
                    '$1' '${2:-stable}' '${3:-main}' \
                    > /etc/apt/sources.list.d/lazy-bootstrap-src.sources"
        else
            env_run_step prepare "enable deb-src" '
out=/etc/apt/sources.list.d/lazy-bootstrap-src.sources
: > "$out"
for f in /etc/apt/sources.list.d/*.sources; do
    [ -e "$f" ] || continue
    case "$f" in *lazy-bootstrap-src.sources) continue;; esac
    sed "s/^Types:.*/Types: deb-src/" "$f" >> "$out"; printf "\n" >> "$out"
done
for f in /etc/apt/sources.list /etc/apt/sources.list.d/*.list; do
    [ -e "$f" ] || continue
    sed -n "s/^deb \(.*\)$/deb-src \1/p" "$f" \
        >> /etc/apt/sources.list.d/lazy-bootstrap-src.list || true
done
[ -s "$out" ] || rm -f "$out"'
        fi
        env_run_step prepare "apt-get update" \
            "DEBIAN_FRONTEND=noninteractive apt-get update -o Acquire::Retries=3"
        sysdeps_install common
    fi
}

# --------------------------------------------------------------------------
# toolchains
# --------------------------------------------------------------------------
TC_CC=""; TC_CXX=""; TC_VERSION=""; TC_SOURCE=""; TC_DROP=""; TC_RUNTIME=""
declare -a TC_ENV=()

toolchain_provision() {
    local id="$1" kind version
    kind="${id%%-*}"; version=""
    case "$id" in *-*) version="${id#*-}" ;; esac
    case "$version" in [0-9]*) ;; *) version="" ;; esac
    case "$kind" in clang) kind=llvm ;; esac

    sysdeps_install "$kind"
    case "$kind" in
        gcc)  toolchain_gcc  "$version" ;;
        llvm) toolchain_llvm "$version" ;;
        filc) toolchain_filc "${version:-$FILC_VERSION}" ;;
        *)    die "unknown toolchain kind: $kind" ;;
    esac
    install_shim
}

toolchain_gcc() {
    local version="$1"
    # preinstalled first: the distro's own compiler is the baseline, and on the
    # host backend reinstalling it would be rude (docs/SPECS.md D-12).
    TC_CC="$(env_run "command -v gcc${version:+-$version} cc 2>/dev/null | head -n1" | tr -d '\n')"
    if [ -z "$TC_CC" ]; then
        if [ "$DISTRO" = alpine ]; then
            env_run_step toolchain "install gcc" "apk add --no-cache gcc g++ musl-dev make"
        else
            env_run_step toolchain "install gcc" \
                "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
                 gcc${version:+-$version} g++${version:+-$version}"
        fi
        TC_CC="$(env_run "command -v gcc${version:+-$version} cc 2>/dev/null | head -n1" | tr -d '\n')"
        TC_SOURCE=distro
    else
        TC_SOURCE=preinstalled
    fi
    [ -n "$TC_CC" ] || die "gcc not available"
    TC_CXX="$(env_run "command -v g++${version:+-$version} c++ 2>/dev/null | head -n1" | tr -d '\n')"
    TC_VERSION="$(env_run "$TC_CC -dumpversion" | tr -d '\n')"
}

toolchain_llvm() {
    local version="$1" major="${1%%.*}"
    if [ "$DISTRO" = alpine ]; then
        env_run_step toolchain "install clang" "apk add --no-cache clang llvm lld compiler-rt"
    else
        env_run_step toolchain "install clang" \
            "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
             clang${major:+-$major} lld${major:+-$major}"
    fi
    TC_CC="$(env_run "command -v clang${major:+-$major} clang 2>/dev/null | head -n1" | tr -d '\n')"
    [ -n "$TC_CC" ] || die "clang not available (the shell edition does not download LLVM tarballs)"
    TC_CXX="$(env_run "command -v clang++${major:+-$major} clang++ 2>/dev/null | head -n1" | tr -d '\n')"
    TC_VERSION="$(env_run "$TC_CC -dumpversion" | tr -d '\n')"
    TC_SOURCE=distro
    if [ -n "$version" ] && [ "${TC_VERSION#$version}" = "$TC_VERSION" ]; then
        warn "asked for clang $version, the distro has $TC_VERSION (recorded as-is)"
    fi
}

toolchain_filc() {
    local version="$1" variant asset url tarball prefix
    # musl -> pizfix, glibc -> /opt/fil. libc6-compat does NOT make it glibc (D-13).
    if [ "$LIBC" = musl ]; then variant=filc; else variant=optfil; fi
    asset="$variant-$version-linux-x86_64.tar.xz"
    url="https://github.com/pizlonator/fil-c/releases/download/v$version/$asset"
    tarball="$CACHE_DIR/downloads/$asset"

    if [ ! -s "$tarball" ]; then
        step_begin fetch "download $asset"
        mkdir -p "$(dirname "$tarball")"
        replay_add curl -fsSL -o "$tarball" "$url"
        curl -fsSL --retry 3 -o "$tarball.part" "$url"
        local rc=$?; step_end "$rc"
        [ "$rc" = 0 ] || die "could not download $url"
        mv "$tarball.part" "$tarball"
    fi

    if [ "$variant" = filc ]; then
        prefix="$TC_ROOT/filc-$version"
        env_run "mkdir -p $prefix" >/dev/null
        env_put "$tarball" "/tmp/$asset"
        env_run_step toolchain "unpack fil-c (pizfix, musl)" \
            "cd $prefix && tar -xJf /tmp/$asset --strip-components=1 && rm -f /tmp/$asset"
        [ "$ENV_RC" = 0 ] || die "could not unpack $asset (is xz declared in ci/system-deps?)"
        env_run_step toolchain "fil-c setup" \
            "cd $prefix
command -v patchelf >/dev/null 2>&1 && sh setup.sh >/dev/null 2>&1
mkdir -p pizfix/os-include && cd pizfix/os-include
[ -e linux ] || ln -sf /usr/include/linux linux 2>/dev/null || true
[ -e asm ] || ln -sf /usr/include/x86_64-linux-gnu/asm asm 2>/dev/null || \
    ln -sf /usr/include/asm asm 2>/dev/null || true
[ -e asm-generic ] || ln -sf /usr/include/asm-generic asm-generic 2>/dev/null || true"
        TC_CC="$prefix/build/bin/clang"; TC_CXX="$prefix/build/bin/clang++"
        TC_RUNTIME="$prefix/pizfix/lib $prefix/pizfix/lib64"
        TC_ENV+=("LD_LIBRARY_PATH=$prefix/pizfix/lib64:$prefix/pizfix/lib")
    else
        # The /opt/fil archive is a wrapper around fil.tar.xz.
        local staging="$CACHE_DIR/filc/optfil-$version"
        mkdir -p "$staging"
        [ -s "$staging/fil.tar.xz" ] || tar -xf "$tarball" -C "$staging" --strip-components=1
        env_run "mkdir -p /opt/fil" >/dev/null
        env_put "$staging/fil.tar.xz" /tmp/fil.tar.xz
        env_run_step toolchain "unpack fil-c (/opt/fil, glibc)" \
            "cd /opt/fil && tar -xJf /tmp/fil.tar.xz --strip-components=1 && rm -f /tmp/fil.tar.xz"
        [ "$ENV_RC" = 0 ] || die "could not unpack fil.tar.xz (is xz declared in ci/system-deps?)"
        TC_CC=/opt/fil/bin/filcc; TC_CXX=/opt/fil/bin/fil++
        TC_RUNTIME="/opt/fil/lib /opt/fil/lib64"
    fi
    TC_VERSION="$version ($variant, clang 20.1.8)"
    TC_SOURCE=binary
    # No LTO plugin ships with the release: drop the distro's LTO flags (D-22).
    TC_DROP='-flto|-flto=*|-ffat-lto-objects|-fno-fat-lto-objects'
    TC_ENV+=("DEB_BUILD_OPTIONS=nolto")
}

# The compiler shim: a PATH-first wrapper so even a hand-written Makefile that
# calls `gcc` ends up in the toolchain we chose (docs/SPECS.md D-11).
install_shim() {
    local filter=""
    [ -n "$TC_DROP" ] && filter="
count=\$#
while [ \"\$count\" -gt 0 ]; do
    arg=\"\$1\"; shift; count=\$((count - 1))
    case \"\$arg\" in
        $TC_DROP)
            [ \"\${LB_SHIM_TRACE:-0}\" != 0 ] && printf '[shim] dropped %s\\n' \"\$arg\" >&2
            continue ;;
    esac
    set -- \"\$@\" \"\$arg\"
done"

    env_run "mkdir -p $SHIM_DIR/bin" >/dev/null
    local name
    for name in cc gcc clang x86_64-linux-gnu-gcc x86_64-alpine-linux-musl-gcc; do
        env_write "$SHIM_DIR/bin/$name" 0755 <<EOF
#!/bin/sh
# lazy-bootstrap compiler shim -> $TC_CC   (dropped: ${TC_DROP:-none})
[ "\${LB_SHIM_TRACE:-0}" != 0 ] && printf '[shim] %s %s\n' "\$0" "\$*" >&2
$filter
exec $TC_CC "\$@"
EOF
    done
    for name in c++ g++ clang++ x86_64-linux-gnu-g++ x86_64-alpine-linux-musl-g++; do
        env_write "$SHIM_DIR/bin/$name" 0755 <<EOF
#!/bin/sh
# lazy-bootstrap compiler shim -> ${TC_CXX:-$TC_CC}
[ "\${LB_SHIM_TRACE:-0}" != 0 ] && printf '[shim] %s %s\n' "\$0" "\$*" >&2
$filter
exec ${TC_CXX:-$TC_CC} "\$@"
EOF
    done

    # A toolchain with its own runtime also needs dpkg to stop asking which .deb
    # owns libpizlo.so (docs/SPECS.md D-23).
    if [ -n "$TC_RUNTIME" ] && [ "$DISTRO" = debian ]; then
        local flags=""; for d in $TC_RUNTIME; do flags="$flags -l$d"; done
        env_write "$SHIM_DIR/bin/dpkg-shlibdeps" 0755 <<EOF
#!/bin/sh
# lazy-bootstrap: this toolchain ships a runtime no .deb owns.
exec /usr/bin/dpkg-shlibdeps$flags --ignore-missing-info "\$@"
EOF
    fi

    ENV_VARS=("CC=$SHIM_DIR/bin/cc" "CXX=$SHIM_DIR/bin/c++" "LB_TOOLCHAIN=$TOOLCHAIN"
              "PATH=$SHIM_DIR/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
              "${TC_ENV[@]}")
}

# Compile and run a hello world: the gate before spending hours on packages.
toolchain_probe() {
    env_write /tmp/lb-probe.c 0644 <<'EOF'
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main(void) {
    char *b = malloc(32);
    if (!b) return 1;
    snprintf(b, 32, "lazy-bootstrap");
    if (strcmp(b, "lazy-bootstrap") != 0) return 2;
    printf("probe ok: %s\n", b);
    free(b);
    return 0;
}
EOF
    env_run_step probe "probe $TOOLCHAIN" \
        'set -e
"$CC" -O1 -o /tmp/lb-probe /tmp/lb-probe.c
/tmp/lb-probe'
    return "$ENV_RC"
}

# --------------------------------------------------------------------------
# building one source package: fetch -> deps -> build
# --------------------------------------------------------------------------
BUILD_STATUS=""; BUILD_ERROR=""; BUILD_SECONDS=0

classify_failure() {
    case "$1" in
        *"Unable to find a source package"*|*"no APKBUILD for"*) printf 'nosource' ;;
        *"Host not in allowlist"*|*"403  Forbidden"*|*"Failed to fetch"*|\
        *"Temporary failure resolving"*|*"Could not resolve host"*|\
        *"unable to select packages"*) printf 'blocked' ;;
        *) printf 'failed' ;;
    esac
}

build_source() {
    local source="$1" start; start="$(date +%s)"
    BUILD_STATUS=failed; BUILD_ERROR=""

    if [ "$DISTRO" = alpine ]; then
        env_run_step fetch "aports checkout $source" \
            "set -e
cd $WORKDIR/aports
found=\"\"
for repo in main community testing; do
    git cat-file -e \"HEAD:\$repo/$source/APKBUILD\" 2>/dev/null && { found=\$repo; break; }
done
[ -n \"\$found\" ] || { echo 'no APKBUILD for $source in aports' >&2; exit 3; }
git sparse-checkout add \"\$found/$source\"
echo \"LB_TREE=$WORKDIR/aports/\$found/$source\""
        if [ "$ENV_RC" != 0 ]; then
            BUILD_STATUS="$(classify_failure "$LAST_OUTPUT")"; BUILD_ERROR="$LAST_OUTPUT"
            BUILD_SECONDS=$(( $(date +%s) - start )); return 0
        fi
        local tree; tree="$(printf '%s' "$LAST_OUTPUT" | sed -n 's/^LB_TREE=//p' | head -n1)"
        env_run_step build "abuild $source" \
            "set -e
cd $tree
export PACKAGER='lazy-bootstrap <noreply@example.invalid>'
export REPODEST=$WORKDIR/packages
abuild -r -K"
    else
        env_run_step fetch "apt-get source $source" \
            "set -e
export DEBIAN_FRONTEND=noninteractive
rm -rf $WORKDIR/src/$source && mkdir -p $WORKDIR/src/$source
cd $WORKDIR/src/$source
apt-get source --only-source $source
tree=\$(find . -maxdepth 1 -mindepth 1 -type d | head -n1)
[ -n \"\$tree\" ] || { echo 'no source tree unpacked' >&2; exit 3; }
echo \"LB_TREE=\$(cd \"\$tree\" && pwd)\""
        if [ "$ENV_RC" != 0 ]; then
            BUILD_STATUS="$(classify_failure "$LAST_OUTPUT")"; BUILD_ERROR="$LAST_OUTPUT"
            BUILD_SECONDS=$(( $(date +%s) - start )); return 0
        fi
        local tree; tree="$(printf '%s' "$LAST_OUTPUT" | sed -n 's/^LB_TREE=//p' | head -n1)"

        env_run_step deps "build-dep $source" \
            "DEBIAN_FRONTEND=noninteractive apt-get build-dep -y --no-install-recommends $source"
        if [ "$ENV_RC" != 0 ]; then
            BUILD_STATUS="$(classify_failure "$LAST_OUTPUT")"; BUILD_ERROR="$LAST_OUTPUT"
            BUILD_SECONDS=$(( $(date +%s) - start )); return 0
        fi

        env_run_step build "dpkg-buildpackage $source" \
            "set -e
cd $tree
DEB_BUILD_OPTIONS=\"\${DEB_BUILD_OPTIONS:-} parallel=\$(nproc) nocheck nodoc\"
export DEB_BUILD_OPTIONS=\"\$(echo \"\$DEB_BUILD_OPTIONS\" | tr -s ' ' | sed 's/^ //;s/ \$//')\"
\"\${CC:-cc}\" --version 2>&1 | head -n2 || true
dpkg-buildpackage -b -uc -us -d --jobs-force=\$(nproc)"
    fi

    if [ "$ENV_RC" = 0 ]; then BUILD_STATUS=ok
    else BUILD_STATUS="$(classify_failure "$LAST_OUTPUT")"; BUILD_ERROR="$LAST_OUTPUT"; fi
    BUILD_SECONDS=$(( $(date +%s) - start ))
}

# --------------------------------------------------------------------------
# report: the same JSON schema the Python driver writes (docs/SPECS.md D-14)
# --------------------------------------------------------------------------
json_escape() {
    python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))' 2>/dev/null || {
        printf '"%s"' "$(sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' | tr -d '\r' | awk '{printf "%s\\n", $0}')"
    }
}
jstr() { printf '%s' "$1" | json_escape; }

write_report() {
    local run_id="$1" dir="$OUT_DIR/$1"
    mkdir -p "$dir"
    {
        printf '{\n'
        printf '  "schema_version": 1,\n'
        printf '  "run_id": %s,\n'          "$(jstr "$run_id")"
        printf '  "started_at": %s,\n'      "$(jstr "$STARTED_AT")"
        printf '  "finished_at": %s,\n'     "$(jstr "$(date -u +%Y-%m-%dT%H:%M:%S+00:00)")"
        printf '  "image": %s,\n'           "$(jstr "$(resolve_image "${IMAGE:-host}")")"
        printf '  "distro": %s,\n'          "$(jstr "${DISTRO_ID:-$DISTRO}")"
        printf '  "backend": %s,\n'         "$(jstr "$BACKEND")"
        printf '  "toolchain": %s,\n'       "$(jstr "$TOOLCHAIN")"
        printf '  "fallback": "",\n'
        printf '  "grouping": "all",\n'
        printf '  "label": %s,\n'           "$(jstr "$TOOLCHAIN")"
        printf '  "toolchains": [{"id": %s, "kind": %s, "version": %s, "source": %s, "cc": %s, "cxx": %s, "ok": true, "detail": %s}],\n' \
            "$(jstr "$TOOLCHAIN")" "$(jstr "${TOOLCHAIN%%-*}")" "$(jstr "$TC_VERSION")" \
            "$(jstr "$TC_SOURCE")" "$(jstr "$TC_CC")" "$(jstr "$TC_CXX")" \
            "$(jstr "driver: sh/lazy-bootstrap.sh $VERSION")"
        printf '  "environment": {"driver": %s, "arch": %s, "libc": %s, "distro_version": %s, "rootfs": %s, "workdir": %s, "system_deps": %s, "generator": "sh"},\n' \
            "$(jstr "$DISTRO")" "$(jstr "$ARCH")" "$(jstr "$LIBC")" "$(jstr "$DISTRO_VERSION")" \
            "$(jstr "$ROOTFS")" "$(jstr "$WORKDIR")" "$(jstr "$SYSTEM_DEPS")"
        printf '  "notes": ['
        local first=1 n
        for n in "${NOTES[@]:-}"; do
            [ -n "$n" ] || continue
            [ "$first" = 1 ] || printf ', '
            printf '%s' "$(jstr "$n")"; first=0
        done
        printf '],\n'
        printf '  "results": [\n'
        printf '%s\n' "${RESULTS_JSON%,}"
        printf '  ]\n}\n'
    } > "$dir/report.json"
    printf '%s' "$dir/report.json"
}

result_json() { # <name> <version> <arch> <source> <status> <seconds> <error>
    RESULTS_JSON="$RESULTS_JSON    {\"package\": {\"name\": $(jstr "$1"), \"version\": $(jstr "$2"), \"arch\": $(jstr "$3"), \"source_name\": $(jstr "$4"), \"source_version\": $(jstr "$2"), \"repo\": \"\"}, \"status\": $(jstr "$5"), \"toolchain\": $(jstr "$TOOLCHAIN"), \"seconds\": $6, \"unit\": \"all\", \"artifacts\": [], \"attempts\": [{\"toolchain\": $(jstr "$TOOLCHAIN"), \"status\": $(jstr "$5"), \"seconds\": $6, \"steps\": [], \"error\": $(jstr "$7")}]},
"
}

# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------
cmd_doctor() {
    say "backends"
    local b
    for b in podman docker bwrap firejail chroot; do
        if command -v "$b" >/dev/null 2>&1; then printf '  [ok ] %-10s %s\n' "$b" "$(command -v "$b")"
        else printf '  [-- ] %-10s not installed\n' "$b"; fi
    done
    printf '  [ok ] %-10s uid=%s\n' host "$(id -u)"
    say "helpers"
    for b in curl tar xz git patchelf mount python3; do
        if command -v "$b" >/dev/null 2>&1; then printf '  [ok ] %-10s\n' "$b"
        else printf '  [-- ] %-10s not installed\n' "$b"; fi
    done
    say "network"
    local h
    for h in https://github.com/ https://mirror.gcr.io/v2/ https://deb.debian.org/debian/dists/ \
             https://dl-cdn.alpinelinux.org/alpine/ http://archive.ubuntu.com/ubuntu/dists/; do
        local code; code="$(curl -sS -o /dev/null -w '%{http_code}' -I --max-time 10 "$h" 2>/dev/null)"
        case "$code" in 2*|3*|401|404|405) printf '  [ok ] %-45s %s\n' "$h" "$code" ;;
                        *) printf '  [-- ] %-45s %s\n' "$h" "$code" ;; esac
    done
}

cmd_inventory() {
    env_open; trap env_close EXIT
    detect_distro
    local total=0
    while IFS=$'\t' read -r name version arch source || [ -n "$name" ]; do
        [ -n "$name" ] || continue
        total=$((total + 1))
        if [ "$source" != "$name" ] && [ -n "$source" ]; then
            printf '  %-34s %-26s  <- %s\n' "$name" "$version" "$source"
        else
            printf '  %-34s %s\n' "$name" "$version"
        fi
    done < <(distro_inventory)
    printf '\n%s binary packages\n' "$total"
}

cmd_rebuild() {
    STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%S+00:00)"
    local run_id; run_id="$(printf '%s-%s-%s' \
        "$(printf '%s' "${IMAGE:-host}" | tr -c 'a-zA-Z0-9._-' '-')" \
        "$(printf '%s' "$TOOLCHAIN" | tr -c 'a-zA-Z0-9._-' '-')" "$(date +%s)")"
    mkdir -p "$OUT_DIR/$run_id"
    replay_init "$OUT_DIR/$run_id/replay/all.sh"

    env_open; trap env_close EXIT
    detect_distro

    say "toolchain: $TOOLCHAIN"
    toolchain_provision "$TOOLCHAIN"
    if ! toolchain_probe; then
        die "toolchain $TOOLCHAIN cannot compile a hello world - fix that first"
    fi
    info "toolchain ok: $TC_CC ($TC_VERSION, from $TC_SOURCE)"

    say "preparing the build environment"
    prepare_builder

    # binary -> source, deduplicated: one build per source package (D-10)
    local -A SOURCE_OF=() VERSION_OF=() ARCH_OF=()
    local -a sources=()
    while IFS=$'\t' read -r name version arch source || [ -n "$name" ]; do
        [ -n "$name" ] || continue
        source="${source:-$name}"
        if [ "${#SELECT[@]}" -gt 0 ]; then
            local keep=0 s
            for s in "${SELECT[@]}"; do
                [ "$s" = "$name" ] || [ "$s" = "$source" ] && keep=1
            done
            [ "$keep" = 1 ] || continue
        fi
        SOURCE_OF["$name"]="$source"; VERSION_OF["$name"]="$version"; ARCH_OF["$name"]="$arch"
        case " ${sources[*]:-} " in *" $source "*) ;; *) sources+=("$source") ;; esac
    done < <(distro_inventory)

    [ "$LIMIT" -gt 0 ] && sources=("${sources[@]:0:$LIMIT}")
    say "rebuilding ${#sources[@]} source package(s)"

    RESULTS_JSON=""
    local ok=0 bad=0 source name
    for source in "${sources[@]}"; do
        build_source "$source"
        case "$BUILD_STATUS" in ok) ok=$((ok + 1)) ;; *) bad=$((bad + 1)) ;; esac
        printf '  %-34s %-9s %ss\n' "$source" "$BUILD_STATUS" "$BUILD_SECONDS"
        for name in "${!SOURCE_OF[@]}"; do
            [ "${SOURCE_OF[$name]}" = "$source" ] || continue
            result_json "$name" "${VERSION_OF[$name]}" "${ARCH_OF[$name]}" "$source" \
                        "$BUILD_STATUS" "$BUILD_SECONDS" "$(printf '%s' "$BUILD_ERROR" | tail -c 2000)"
        done
    done

    local path; path="$(write_report "$run_id")"
    say "done: $ok ok, $bad failed"
    printf 'report: %s\n' "$path"
    printf 'replay: %s\n' "$REPLAY"
    printf '\nrender it with:\n  ./lazy-bootstrap report %s --format html -o report.html\n' \
        "$OUT_DIR/$run_id"
    [ "$bad" -eq 0 ]
}

usage() {
    cat <<EOF
$SELF $VERSION - rebuild the packages of a distro image (shell edition)

  $SELF doctor
  $SELF inventory <image> [options]
  $SELF rebuild   <image> [options]

Options
  -b, --backend NAME       host | chroot | bwrap | firejail | podman | docker
      --rootfs SPEC        image[:REF] | dir:PATH | none
      --rootfs-path PATH   where to materialise the rootfs
      --workdir PATH       build directory inside the environment
  -t, --toolchain ID       gcc | llvm[-VER] | filc[-VER]        (default: gcc)
      --package NAME       only this package/source (repeatable)
      --limit N            build at most N source packages
      --registry-mirror H  e.g. mirror.gcr.io
      --source-mirror SPEC apt: "URL suite components"; apk: aports branch
      --system-deps POLICY off | target | host                  (default: target)
      --out-dir DIR        where reports go                     (default: runs)
      --timeout SECONDS    per package                          (default: 1800)
  -d, --debug              repeatable: -d steps, -dd payloads, -ddd full output

Environment
  LB_DEBUG=0..3            same as --debug
  LB_SHIM_TRACE=1          echo every compiler invocation from inside the build
EOF
}

# --------------------------------------------------------------------------
# argument parsing
# --------------------------------------------------------------------------
NOTES=()
COMMAND="${1:-}"; shift || true
case "$COMMAND" in
    -h|--help|help|"") usage; exit 0 ;;
    doctor|inventory|rebuild) ;;
    *) die "unknown command: $COMMAND (try --help)" ;;
esac

while [ $# -gt 0 ]; do
    case "$1" in
        -b|--backend)        BACKEND="$2"; shift 2 ;;
        --rootfs)            ROOTFS="$2"; shift 2 ;;
        --rootfs-path)       ROOTFS_PATH="$2"; shift 2 ;;
        --workdir)           WORKDIR="$2"; shift 2 ;;
        -t|--toolchain)      TOOLCHAIN="$2"; shift 2 ;;
        --package)           SELECT+=("$2"); shift 2 ;;
        --limit)             LIMIT="$2"; shift 2 ;;
        --registry-mirror)   REGISTRY_MIRROR="$2"; shift 2 ;;
        --source-mirror)     SOURCE_MIRROR="$2"; shift 2 ;;
        --system-deps)       SYSTEM_DEPS="$2"; shift 2 ;;
        --out-dir)           OUT_DIR="$2"; shift 2 ;;
        --cache-dir)         CACHE_DIR="$2"; shift 2 ;;
        --timeout)           TIMEOUT="$2"; shift 2 ;;
        -d|--debug)          LB_DEBUG=$((LB_DEBUG + 1)); shift ;;
        -h|--help)           usage; exit 0 ;;
        -*)                  die "unknown option: $1" ;;
        *)                   IMAGE="$1"; shift ;;
    esac
done

[ "$BACKEND" = host ] || [ "$COMMAND" = doctor ] || [ -n "$IMAGE" ] || \
    case "$ROOTFS" in dir:*|none) ;; *) die "an image is required" ;; esac

case "$COMMAND" in
    doctor)    cmd_doctor ;;
    inventory) cmd_inventory ;;
    rebuild)   cmd_rebuild ;;
esac
